USE accidents_nyc;
DROP TABLE all_accidents;
CREATE TABLE all_accidents (
			ROW_ID INTEGER DEFAULT NULL,
			CRASH_DATE DATE,
            CRASH_TIME TIME DEFAULT NULL,
            BOROUGH VARCHAR(255) DEFAULT NULL,
            ZIP_CODE INTEGER DEFAULT NULL,
            LATITUDE DECIMAL(7, 4) DEFAULT NULL,
            LONGITUDE DECIMAL(7, 4) DEFAULT NULL,
--             LOCATION POINT SRID 4326 default null,
			STREET_NAME	VARCHAR(255) DEFAULT NULL,
            INTERSECTING_STREET_NAME VARCHAR(255) DEFAULT NULL,
            OFF_STREET_NAME	VARCHAR(255) DEFAULT NULL,
            NUMBER_OF_PERSONS_INJURED INTEGER DEFAULT NULL,
            NUMBER_OF_PERSONS_KILLED INTEGER DEFAULT NULL,
            NUMBER_OF_PEDESTRIANS_INJURED INTEGER DEFAULT NULL,
            NUMBER_OF_PEDESTRIANS_KILLED INTEGER DEFAULT NULL,
            NUMBER_OF_CYCLIST_INJURED INTEGER DEFAULT NULL,
            NUMBER_OF_CYCLIST_KILLED INTEGER DEFAULT NULL,
            NUMBER_OF_MOTORIST_INJURED INTEGER DEFAULT NULL,
            NUMBER_OF_MOTORIST_KILLED INTEGER DEFAULT NULL,
            CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR(255) DEFAULT NULL,
            CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR(255) DEFAULT NULL,
            CONTRIBUTING_FACTOR_VEHICLE_3 VARCHAR(255) DEFAULT NULL,
            CONTRIBUTING_FACTOR_VEHICLE_4 VARCHAR(255) DEFAULT NULL,
            CONTRIBUTING_FACTOR_VEHICLE_5 VARCHAR(255) DEFAULT NULL,
            COLLISION_ID INTEGER PRIMARY KEY DEFAULT 0,
            VEHICLE_TYPE_CODE_1	VARCHAR(255) DEFAULT NULL,
            VEHICLE_TYPE_CODE_2	VARCHAR(255) DEFAULT NULL,
            VEHICLE_TYPE_CODE_3	VARCHAR(255) DEFAULT NULL,
            VEHICLE_TYPE_CODE_4	VARCHAR(255) DEFAULT NULL,
            VEHICLE_TYPE_CODE_5 VARCHAR(255) DEFAULT NULL);

LOAD DATA
INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\NYC_Accidents_2020_1.csv'
INTO TABLE all_accidents
FIELDS TERMINATED BY ','
optionally ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 lines
(@vROW_ID,@vCRASH_DATE, @vCRASH_TIME, @vBOROUGH, @vZIP_CODE,
@vLATITUDE, @vLONGITUDE, @vSTREET_NAME, @vINTERSECTING_STREET_NAME, @vOFF_STREET_NAME,
 @vNUMBER_OF_PERSONS_INJURED, @vNUMBER_OF_PERSONS_KILLED, @vNUMBER_OF_PEDESTRIANS_INJURED,
 @vNUMBER_OF_PEDESTRIANS_KILLED, @vNUMBER_OF_CYCLIST_INJURED,
 @vNUMBER_OF_CYCLIST_KILLED, @vNUMBER_OF_MOTORIST_INJURED, @vNUMBER_OF_MOTORIST_KILLED,
 @vCONTRIBUTING_FACTOR_VEHICLE_1, @vCONTRIBUTING_FACTOR_VEHICLE_2, @vCONTRIBUTING_FACTOR_VEHICLE_3, @vCONTRIBUTING_FACTOR_VEHICLE_4,
 @vCONTRIBUTING_FACTOR_VEHICLE_5, @vCOLLISION_ID, @vVEHICLE_TYPE_CODE_1, @vVEHICLE_TYPE_CODE_2, @vVEHICLE_TYPE_CODE_3, @vVEHICLE_TYPE_CODE_4, @vVEHICLE_TYPE_CODE_5)

SET
ROW_ID = NULLIF(@vROW_ID,''),
CRASH_DATE = NULLIF(@vCRASH_DATE,''),
CRASH_TIME= NULLIF(@vCRASH_TIME,''),
BOROUGH = NULLIF(@vBOROUGH,''),
ZIP_CODE = NULLIF(@vZIP_CODE,''),
LATITUDE = NULLIF(@vLATITUDE,''),
LONGITUDE = NULLIF(@vLONGITUDE,''),
STREET_NAME	= NULLIF(@vSTREET_NAME,''),
INTERSECTING_STREET_NAME = NULLIF(@vINTERSECTING_STREET_NAME,''),
OFF_STREET_NAME = NULLIF(@vOFF_STREET_NAME,''),
NUMBER_OF_PERSONS_INJURED = NULLIF(@vNUMBER_OF_PERSONS_INJURED,''),
NUMBER_OF_PERSONS_KILLED = NULLIF(@vNUMBER_OF_PERSONS_KILLED,''),
NUMBER_OF_PEDESTRIANS_INJURED = NULLIF(@vNUMBER_OF_PEDESTRIANS_INJURED,''),
NUMBER_OF_PEDESTRIANS_KILLED = NULLIF(@vNUMBER_OF_PEDESTRIANS_KILLED,''),
NUMBER_OF_CYCLIST_INJURED = NULLIF(@vNUMBER_OF_CYCLIST_INJURED,''),
NUMBER_OF_CYCLIST_KILLED  = NULLIF(@vNUMBER_OF_CYCLIST_KILLED,''),
NUMBER_OF_MOTORIST_INJURED = NULLIF(@vNUMBER_OF_MOTORIST_INJURED,''),
NUMBER_OF_MOTORIST_KILLED = NULLIF(@vNUMBER_OF_MOTORIST_KILLED,''),
CONTRIBUTING_FACTOR_VEHICLE_1 = NULLIF(@vCONTRIBUTING_FACTOR_VEHICLE_1,''),
CONTRIBUTING_FACTOR_VEHICLE_2 = NULLIF(@vCONTRIBUTING_FACTOR_VEHICLE_2,''),
CONTRIBUTING_FACTOR_VEHICLE_3= NULLIF(@vCONTRIBUTING_FACTOR_VEHICLE_3,''),
CONTRIBUTING_FACTOR_VEHICLE_4 = NULLIF(@vCONTRIBUTING_FACTOR_VEHICLE_4,''),
CONTRIBUTING_FACTOR_VEHICLE_5 = NULLIF(@vCONTRIBUTING_FACTOR_VEHICLE_5,''),
COLLISION_ID = NULLIF(@vCOLLISION_ID,''),
VEHICLE_TYPE_CODE_1	= NULLIF(@vVEHICLE_TYPE_CODE_1,''),
VEHICLE_TYPE_CODE_2 = NULLIF(@vVEHICLE_TYPE_CODE_2,''),
VEHICLE_TYPE_CODE_3 = NULLIF(@vVEHICLE_TYPE_CODE_3,''),
 VEHICLE_TYPE_CODE_4 = NULLIF(@vVEHICLE_TYPE_CODE_4,''),
 VEHICLE_TYPE_CODE_5 = NULLIF(@vVEHICLE_TYPE_CODE_5,'')
;
